exp_name: SPELL_VS_SumMe_default
model_name: SPELL
graph_name: SumMe_20_0
dataset: SumMe
loss_name: bce_logit
use_spf: False
use_ref: False

num_modality: 1
channel1: 256
channel2: 256
final_dim: 1
num_att_heads: 0
dropout: 0.5
lr: 0.0001
wd: 0.00001
batch_size: 1
sch_param: 5
num_epoch: 200
sample_rate: 1
