exp_name: SPELL_VS_TVSum_default
model_name: SPELL
graph_name: TVSum_10_0
dataset: TVSum
loss_name: bce_logit
use_spf: False
use_ref: False

num_modality: 1
channel1: 64
channel2: 64
final_dim: 1
num_att_heads: 0
dropout: 0.5
lr: 0.00005
wd: 0
batch_size: 1
sch_param: 5
num_epoch: 140
sample_rate: 1
